### ISSUE TITLE
User commands

### ISSUE THREAD

**Issue by EngineerBean** [rexxar-tc/EssentialsPlugin#12]
1st, I wanted to thankyou for your efforts in reviving this project. I've been running a Space Engineers server for the last year and a half, making good use of SESE. Chessmaster, Tyrsis, Doxdexahedron and yourself have provided us admins with a frontend that goes way beyond Keen have ever provided for us, and it is hard to do without. Keep up the great work, it is very much appreciated.

Just a little issue, no biggie..Commands such as /utility grids etc are being echoed back in chat.

Havn't found any other major bugs yet, and all seems to be working quite well, you have done well with your work on concealment. Is working great. My world running on the DS has over 600 cube grids. Having concealment operating has really helped the server simpseed and improving gameplay for all users.

**Comment by rexxar-tc** [comment]
Since we have new netcode coming up, a lot of stuff in the backend is likely to change. Right now I'm focusing on critical issues and new features; I don't want to waste the time fixing a whole bunch of stuff that's going to break when new netcode comes in.

Once we get the update, I'll look into a way to completely intercept chat messages, but for now users will just have to deal with seeing admin commands.

**Comment by EngineerBean** [comment]
no worries at all, thx for your reply
