### ISSUE TITLE
[v1.13.4.186-alpha] CommRelayOutput grids

### ISSUE THREAD

**Issue by EngineerBean** [rexxar-tc/EssentialsPlugin#21]
I've noticed in my Cube Grid list that CommRelayOutput blocks are being created but not being removed, and multiple players have been finding the blocks near their builds. One player reported that he had 6 unwelded beacons near his base.

**Comment by rexxar-tc** [comment]
Goddammit. Okay, I'm working on it.

**Comment by rexxar-tc** [comment]
What's your server called? I'd like to take a look at what's happening.

**Comment by EngineerBean** [comment]
spaceengineers.com.au

I have also had reports of  the MOTD popping up at random times, not only when a player joins..i've noticed it sometimes when flying back to my station for example

**Comment by rexxar-tc** [comment]
The MOTD is probably showing up at random because the beacons aren't being deleted properly. Essentials can't communicate directly with the client, so we create the relay beacon to send data like dialog windows.

It looks like you have Midspace's admin helper commands mod. I don't know exactly how his mod interacts with mine, but it isn't good. In your case, it looks like his mod is completely overriding mine, which is what's going wrong.

Sometimes when the server deletes a grid, the client doesn't get the message. The essentials mod is supposed to delete the relays on its own to take care of this problem. Right now there is a lot of trouble syncing data between server and clients, and it's causing problems all throughout Essentials.

Whatever Midspace is doing is completely incompatible with the Essentials mod, and there really isn't anything I can do about it. So, until I can get the sync issue fixed, or we get new netcode, disable either the MOTD or Midspace's mod.
