### ISSUE TITLE
Feature Suggestion: Exporting of grids from cleanup and other 

### ISSUE THREAD

**Issue by SilentSymphony** [rexxar-tc/EssentialsPlugin#26]
Often enough when using cleanup especially automated cleanup mistakes happen and players need a ship restored, For a long time now this involves opening a backup of the map and searching for the players ship which is not so bad if you have the process down however if the ships deleted by these cleanups were exported similar to how the backups are it would allow server admins to much more quickly find a players ship and restore it as only the deleted objects would be there.

It is not uncommon for me to use a gigabyte or more of bandwith on a bad day downloading map files and other things, an archive of exported ships would be very small in a zip, they could be archived by date deleted and with a tag labeling what kind of process deleted the grids for ease of use.

I don't know if other servers offer restoration of grids to players but i think its essential given the state of the game and how frequently bugs can destroy players hard work.

I feel this could possibly take away from the performance of the server but the utility of it could be worth the sacrifice depending on how you run your server.

**Comment by rexxar-tc** [comment]
This could get very messy very quick. Exporting grids isn't a problem; it's just XML. The problem is pretty simple; disk space. If we export every grid that gets cleaned up, disk usage will run out of control. We'd have to be **very** aggressive with how we handle exported items. e.g., don't export anything named Small Ship*, Large Ship*, or Platform*. Nothing below 100 blocks, and no duplicates; any identical names overwrite the older file. Exported grids have to be zipped, and must be cleaned out after so many days.

Performance impact is meh. SESE runs in a thread separate from the server, so if we do heavy data crunching in SESE, it doesn't affect game performance all that much.

I'm gonna say no to this one. I don't think it's a good idea or altogether that necessary. It's an admin's job to make sure cleanup rules don't take out user ships, and to make users understand what the rules are.
